apiVersion: v1
kind: Service
metadata:
  name: caspar-app
  labels:
    app: caspar-app
spec:
  selector:
    app: caspar-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caspar-app
  labels:
    app: caspar-app
spec:
  selector:
    matchLabels:
      app: caspar-app
  template:
    metadata:
      labels:
        app: caspar-app
    spec:
      containers:
        - name: caspar-app
          image: caspar-app
          ports:
            - containerPort: 5000
          imagePullPolicy: "Always"